name: rexuiz
version: 2.5.2-210903
summary: Single and Multiplayer First Person Shooter Game
description: |
  Successor of Nexuiz Classic(r)(tm). Fast paced shooter inspired by
  old school FPS games.
confinement: strict
icon: rexuiz.png
base: core18
grade: stable
architectures:
  - build-on: amd64
    run-on: amd64
parts:
  rexuiz:
    plugin: dump
    source: https://downloads.sourceforge.net/project/rexuiz/Rexuiz-$SNAPCRAFT_PROJECT_VERSION.zip
    stage-packages:
      - libcurl4
      - libfreetype6
      - libglu1-mesa
      - libpulse0
      - libsdl2-2.0-0
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
      - libxext6
      - libxpm4
      - libxxf86vm1
    prime:
      - -Rexuiz/Rexuiz.app/
      - -Rexuiz/RexuizLauncher*
      - -Rexuiz/*.exe
      - -Rexuiz/bin32
      - -Rexuiz/bin64
      - -Rexuiz/sources
  desktop:
    plugin: dump
    source: .
    organize:
      rexuiz.desktop: usr/share/applications/rexuiz.desktop
      rexuiz.png: usr/share/icons/hicolor/128x128/rexuiz.png
    prime:
      - -rexuiz-snap-wrapper.sh
  wrapper:
    plugin: dump
    source: .
    override-build: |
      install -D -m 755 rexuiz-snap-wrapper.sh $SNAPCRAFT_PART_INSTALL/bin/rexuiz-snap-wrapper.sh
apps:
  Rexuiz:
    extensions: [gnome-3-34]
    command: rexuiz-snap-wrapper.sh
    environment:
      SDL_AUDIODRIVER: pulseaudio
    plugs:
      - audio-playback
      - network
      - network-bind
      - opengl
      - wayland
      - x11
      - desktop
      - desktop-legacy
    desktop: usr/share/applications/rexuiz.desktop
